version: '3.8'

services:
  webfetch-mcp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: webfetch-mcp:latest
    container_name: webfetch-mcp-server
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      
    # Resource limits
    mem_limit: 512m
    memswap_limit: 512m
    cpus: 1.0
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem (with temp directories)
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    
    # Network mode (can be adjusted based on needs)
    network_mode: bridge
    
    # Labels for organization
    labels:
      - "app=webfetch-mcp"
      - "version=1.0.0"
      - "description=MCP Server for Web Data Fetching"
